services:
     bos_api:
         class: BOS\ApiBundle\Services\ApiService
         arguments: ['@service_container']
         tags:
             - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }